/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BL.Entities.Oferta;
import BL.Entities.Persona;
import BL.Entities.Publicacion;
import BL.Helpers.DatabaseService;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class PanelNewOffer extends javax.swing.JPanel {

    private final Persona persona;
    private final Publicacion publicacion;
    private final DatabaseService db;
    private final JFrame parent;
    
    /**
     * Creates new form PanelNewOffer
     */
    public PanelNewOffer(Persona persona, Publicacion publicacion, DatabaseService db, JFrame parent) {
        initComponents();
        this.persona = persona;
        this.publicacion = publicacion;
        this.db = db;
        this.parent = parent;
        
        lblName.setText(publicacion.getNombreProducto());
        try {
            List<Publicacion> listaPublicaciones = this.db.getPublicaciones(this.persona);
            mostrarPublicacionesEnTabla(misPublicaciones, listaPublicaciones);
            mostrarPublicacionesEnTabla(publicacionesOfrecidas, null);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void mostrarPublicacionesEnTabla(javax.swing.JTable table, List<Publicacion> listaPublicaciones) throws SQLException {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("#");
        tableModel.addColumn("Cdad.");
        tableModel.addColumn("Nombre");
        tableModel.addColumn("Descripción");
        tableModel.addColumn("U$C");
        tableModel.addColumn("");
        
        if (listaPublicaciones != null && listaPublicaciones.size() > 0) {
            Object[] row = new Object[6];

            for (int i = 0; i < listaPublicaciones.size(); i++) {
                row[0] = listaPublicaciones.get(i).getId();
                row[1] = listaPublicaciones.get(i).getCantidad();
                row[2] = listaPublicaciones.get(i).getNombreProducto();
                row[3] = listaPublicaciones.get(i).getDescripcion();
                row[4] = listaPublicaciones.get(i).getValorEstimado();
                
                /*
                String image = listaPublicaciones.get(i).getImagen();
                if (image != null) {
                    byte[] decodedBytes = Base64.getDecoder().decode(image);
                    Path destinationFile = Paths.get("", "myImage.jpg");
                    Files.write(destinationFile, decodedBytes);
                    try {
                        fos = new FileOutputStream(file);
                        fos.write(decodedBytes);
                        fos.close();
                        ImageIcon targetImg = ResizeImage(file.getPath());
                        row[5] = targetImg;
                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                    }
                }
                */
                
                tableModel.addRow(row);
            }
        }
        
        table.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOffer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        publicacionesOfrecidas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        misPublicaciones = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ucucoinsTxt = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Mis publicaciones");

        jLabel2.setText("Publicaciones ofrecidas");

        btnOffer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOffer.setForeground(new java.awt.Color(255, 102, 102));
        btnOffer.setText("Ofertar");
        btnOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfferActionPerformed(evt);
            }
        });

        publicacionesOfrecidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(publicacionesOfrecidas);

        misPublicaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(misPublicaciones);

        jLabel3.setText("UCUcoins ofrecidas junto con la oferta: ");

        btnSend.setText("=>");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblName.setText("nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ofertar por:");

        btnBack.setText("<=");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ucucoinsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(304, 304, 304))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblName))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnSend)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOffer)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ucucoinsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        exchangeRows(misPublicaciones, publicacionesOfrecidas);
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfferActionPerformed
        DefaultTableModel model = (DefaultTableModel) publicacionesOfrecidas.getModel();
        int rows = model.getRowCount();
        
        List<Publicacion> publicaciones = new ArrayList<>();
        for (int row = 0; row < rows; row++) {
            publicaciones.add(new Publicacion((int) model.getValueAt(row, 0)));
        }
        
        int ucuCoins; 
        try {
            ucuCoins = Integer.parseInt(ucucoinsTxt.getText());
        } catch (NumberFormatException e) {
            ucuCoins = 0;
        }
        
        try {
            Oferta oferta = new Oferta(this.publicacion.getId(), null, 0, this.persona.getCi(), ucuCoins, publicaciones);
            this.db.insertarOferta(oferta);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnOfferActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        exchangeRows(publicacionesOfrecidas, misPublicaciones);
    }//GEN-LAST:event_btnBackActionPerformed

    private void exchangeRows(javax.swing.JTable from, javax.swing.JTable to) {
        try {
            int row = from.getSelectedRow();
            if (row > -1) {
                DefaultTableModel modelFrom = (DefaultTableModel) from.getModel();
                DefaultTableModel modelTo = (DefaultTableModel) to.getModel();
                int columns = modelFrom.getColumnCount();
                Object[] insertRow = new Object[columns];
                for (int col = 0; col < columns; col++) {
                    insertRow[col] = modelFrom.getValueAt(row, col);
                }
                modelTo.addRow(insertRow);
                modelFrom.removeRow(row);
                
                from.setModel(modelFrom);
                to.setModel(modelTo);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOffer;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable misPublicaciones;
    private javax.swing.JTable publicacionesOfrecidas;
    private javax.swing.JTextField ucucoinsTxt;
    // End of variables declaration//GEN-END:variables
}
