/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BL.Entities.Mensaje;
import BL.Entities.Persona;
import BL.Entities.Publicacion;
import BL.Helpers.DatabaseService;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Administrador
 */
public class PanelSendMessage extends javax.swing.JPanel {

    JFrame frame;
    DatabaseService db;
    Persona pEnvia;
    Persona pRecibe;
    Publicacion pub;

    /**
     * Creates new form PanelConfirmation
     *
     * @param frame
     * @param db
     * @param pEnvia
     * @param pRecibe
     */
    PanelSendMessage(JFrame frameDialog, DatabaseService db, Persona persona, Persona pRecibe, Publicacion pub) {
        this.pEnvia = persona;
        this.pRecibe = pRecibe;
        this.frame = frameDialog;
        this.db = db;
        this.pub = pub;
        initComponents();
        jLabel1.setText("Enviar mensaje a " + pRecibe.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnEnviarMensaje = new javax.swing.JButton();
        contenidoMensaje = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Enviar mensaje a");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 102, 102));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEnviarMensaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEnviarMensaje.setForeground(new java.awt.Color(0, 255, 0));
        btnEnviarMensaje.setText("ENVIAR");
        btnEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajeActionPerformed(evt);
            }
        });

        contenidoMensaje.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        contenidoMensaje.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contenidoMensaje.setText("Escribe el mensaje aqui...");
        contenidoMensaje.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(189, Short.MAX_VALUE)
                        .addComponent(btnEnviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contenidoMensaje)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenidoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajeActionPerformed
        Mensaje mensaje = new Mensaje(contenidoMensaje.getText(), pub.getId(), pEnvia.getCi(), pRecibe.getCi(), false, LocalDateTime.now());
        boolean isConnectedWithDB = this.db.connectToDB();
        if (isConnectedWithDB) {
            try {
                this.db.insertNewMessage(mensaje);
                this.db.closeConnectionDB();

                PanelSucces panel = new PanelSucces(this.frame, "Mensaje enviado con éxito.");
                JDialog dialog = new JDialog(this.frame, true);
                dialog.setSize(panel.getPreferredSize());
                dialog.setLocationRelativeTo(null);
                dialog.getContentPane().add(panel);
                dialog.setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(PanelSendMessage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnEnviarMensajeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.frame.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JTextField contenidoMensaje;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
